AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TextractReceiptCapture

Parameters:
  ReceiptBucket:
    Type: String
    Description: The name of the S3 Bucket to create
  SourceCodeBucket:
    Type: String
    Description: The name of the S3 Bucket with lambda function code
  SourceCodeKey:
    Type: String
    Description: The name of the S3 object contain source code

Resources:
  SourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ReceiptBucket
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        -
          Key: Description
          Value: Textract receipt capture prototype

  LambdaTextractRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: textract-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - textract.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonTextractFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AWSLambdaExecute
        - !Ref LambdaPolicy

  LambdaPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: textract-lambda-policy
      Description: 'Managed policy for lambdas'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: "Allow"
            Action:
              - "s3:PutObject*"
              - "s3:GetBucket*"
              - "s3:GetObject*"
            Resource:
              !Sub |-
                arn:aws:s3:::${ReceiptBucket}:/*

  TextractParserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: textract-receipt-parser-lambda
      Code:
        S3Bucket: !Ref SourceCodeBucket
        S3Key: !Ref SourceCodeKey
      Handler: main.lambda_handler
      Runtime: python3.8
      Timeout: 20
      Role:
        Fn::GetAtt:
          - LambdaTextractRole
          - Arn