
AWSTemplateFormatVersion: "2010-09-09"
Resources: 
  CustomerProfileTable: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "index"
          AttributeType: "N"
      KeySchema: 
        - 
          AttributeName: "index"
          KeyType: "HASH"
      TableName: "rockhistory-archive"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
          
